apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.2
    chart: grafana
    helm:
      parameters:
        -
          name: "service.type"
          value: "LoadBalancer"
        -
          name: "service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-internal"
          value: "true"
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

