apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.8.3
    chart: loki-stack
    helm:
      parameters:
#        -
#          name: "grafana.enabled"
#          value: "true"
        -
          name: "prometheus.enabled"
          value: "true"
        -
          name: "prometheus.server.persistentVolume.enabled"
          value: "false"
        -
          name: "prometheus.alertmanager.persistentVolume.enabled"
          value: "false"
#        -
#          name: "grafana.service.type"
#          value: "LoadBalancer"
#        -
#          name: "grafana.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-internal"
#          value: "true"
#        -
#          name: "grafana.image.tag"
#          value: "9.2.2"
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

