apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.8.4
    chart: loki-stack
    helm:
      values: |
        grafana:
          enabled: "true"
          image:
            tag: "9.2.2"
          service:
            type: "LoadBalancer"
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        
            dashboards:
              default:
                loki:
                  file: dashboards/loki.json
                prometheus:
                  file: dashboards/prometheus.json
              

        prometheus:
          enabled: "true"
          server:
            persistentVolume:
              enabled: "false"
          alertmanager:
            persistentVolume:
              enabled: "false"
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

