grafana:
  enabled: "true"
  image:
    tag: "9.2.2"
  service:
    type: "LoadBalancer"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

prometheus:
  enabled: "true"
  server:
    persistentVolume:
      enabled: "false"
  alertmanager:
    persistentVolume:
      enabled: "false"